### ISSUE TITLE
Extra info on The-Colorlight-i5-as-FPGA-development-board

### ISSUE THREAD

**Issue by pauluzs** [tomverbeure/tomverbeure.github.io#10]
Since not everyone uses twitter, lets hit you here with some extra info after reading the article.
After some searching there are some more led/dev-board in this 200 pin SODIMM form-factor.

Here is a list of the boards with their fpga part numbers as far i could find, albeit not all lattice.:
iCESugar-Pro   board	Lattice ECP5-LFE5U-25F-6BG256C
i5  colorlight board		Lattice ECP5-LFE5U-25F-6BG381C
i6  colorlight board		Lattice ECP3-LFE3-35EA-6FN484C
i9  colorlight board		Lattice ECP5-LFE5U-45F-6BG381C
i9+ colorlight board		Xilinx  XC7AA50T-FGG484ABX1909
linsn mini901  board	Xilinx  XC6SLX16-CSG324DIV1645
Novastar armor a8          Rare and no part numbers found.

There are 2 Breakout Boards
[i- series Development Board](https://www.aliexpress.com/item/1005001686186007.html
) (Hasn't got the analog pins broken out)
[Dual-1000M-Ethernet Board(](https://www.aliexpress.com/item/1005002080383026.html)On order, not sure if analog pins are broken out) 

About these pins 21 mystery pins, Related to the 8 channel analog multiplexers:
Not 100% sure about this, but there are add-on sensors for led modules, which measure i.e:
Temperature, light intensity, and dew-point if i'm correct. 
Could it be these are in a RC network and then multiplexed into a [Sigma-Delta ADC](https://www.latticesemi.com/view_document?document_id=35762) ?

**Comment by tomverbeure** [comment]
Added to the list of references at the bottom of the article.

Bedankt!
