### ISSUE TITLE
Video timings calculator: add modeline

### ISSUE THREAD

**Issue by ValdikSS** [tomverbeure/tomverbeure.github.io#17]
Hello, just found your video timings calculator, it's very useful.
Could you please add modeline generation to it? It should be very easy, just a string in the following format:

```
Modeline "modeline name" pclk hdisp hsyncstart hsyncend htotal vdisp vsyncstart vsyncend vtotal [flags]
Flags (optional): +HSync, -HSync, +VSync, -VSync, Interlace, DoubleScan, CSync, +CSync, -CSync
```

Example:
```
    # 1920x1080x59.93 @ 66.587kHz
    Modeline "1920x1080x59.93"  138.500000  1920 1968 2000 2080  1080 1083 1087 1111  +HSync -VSync
```

**Comment by ValdikSS** [comment]
The calculator should show vertical and horizontal polarity, right now it doesn't. And it would be useful to be able to enter fractional refresh rate.

**Comment by tomverbeure** [comment]
> Could you please add modeline generation to it? It should be very easy, just a string in the following format:

Done! Though I didn't add CSync and DoubleScan.

> The calculator should show vertical and horizontal polarity, right now it doesn't.

Done!

> And it would be useful to be able to enter fractional refresh rate.

Done! 

In fact, it was always possible to enter fractional refresh rates. It's just that there'd be an error message, but the rest of the code ignored that message...

Tom
