### ISSUE TITLE
PMOD_P3B_IO4 wrong pin assignment on i5 extension board

### ISSUE THREAD

**Issue by derekmulcahy** [tomverbeure/tomverbeure.github.io#19]
Hi Tom,

The pin assignment for PMOD_PB3_IO4 on you very useful SVG for the i5 extension board should be A3 and not A12. This is according to the schematic and also verified on the extension board that I have.

Cheers,
Derek

**Comment by tomverbeure** [comment]
Thanks!

Fixed with 4d3a54a6f6c76c0e71407ac90130fa8e87c77626. I hope this didn't cause too much trouble!
