### ISSUE TITLE
Hi, why is the post "2019-12-12-Sipeed-Tang-Nano-Getting-Started.md"  not showing on tomverbeure.github.io? Is it a bug?

### ISSUE THREAD

**Issue by TurnOffNOD** [tomverbeure/tomverbeure.github.io#24]
Hi, I searched about Sipeed Tang Nano and found this post: github.com/tomverbeure/tomverbeure.github.io/blob/tang_nano/_posts/2019-12-12-Sipeed-Tang-Nano-Getting-Started.md , but when I read the personal blog tomverbeure.github.io , this post is not showing.
Is it a bug?

**Comment by tomverbeure** [comment]
I create a separate branch for each topic about which I might one day write a blog post, and write down notes so that I don't forget what I did. The file that you found is on the `tang_nano` branch, but I never wrote the blog post.

Tom

**Comment by TurnOffNOD** [comment]
> I create a separate branch for each topic about which I might one day write a blog post, and write down notes so that I don't forget what I did. The file that you found is on the `tang_nano` branch, but I never wrote the blog post.
> 
> Tom

Thanks for replying
