### ISSUE TITLE
Regarding Your Post "Reed-Solomon Error Correcting Codes from the Bottom Up"

### ISSUE THREAD

**Issue by kannanwisen** [tomverbeure/tomverbeure.github.io#38]
Hi,

Your article is really informative and fantastic explanation.

I think there is one typing error in the below statement

![image](https://github.com/tomverbeure/tomverbeure.github.io/assets/27722774/1718c0d1-4706-48e0-8b70-c5592f88a53f)

I feel the below equation is correct

![image](https://github.com/tomverbeure/tomverbeure.github.io/assets/27722774/bc97922c-f83b-499b-95f5-571d48f96009)

Thanks

Kannan.S

**Comment by tomverbeure** [comment]
Fixed.

Thanks!
Tom
