### ISSUE TITLE
Video Timings Calculator: Add custom modeline

### ISSUE THREAD

**Issue by haarp** [tomverbeure/tomverbeure.github.io#40]
Hey,

the Video Timings Calculator is good, the best online calcs I've seen so far!

One thing I sorely miss tho. You offer convenient modelines, but not the modeline from the custom column. Why? Easily user tweakable modeline is pretty much the point of having custom settings! :)

Would be great if you could add that one. Thanks a lot!

**Comment by tomverbeure** [comment]
Hi,

Done! That was a very simple thing to add.

Thanks!
Tom

**Comment by haarp** [comment]
Perfect, thanks a lot!
