### ISSUE TITLE
A bug about polarity

### ISSUE THREAD

**Issue by xqworld** [tomverbeure/tomverbeure.github.io#41]
Hi, Tom

onpage  https://tomverbeure.github.io/video_timings_calculator
I found that sometimes the polarity of VIC timing calculated was wrong, such as 720x480p@60. Then, I guess there may be an issue with ignoring the case when calculating the timing here, could you please take a moment to fix it?

```
H_FRONT_PORCH           = vic_timing['h_front'];
H_SYNC                  = vic_timing['h_sync'];
H_BACK_PORCH            = vic_timing['h_back'];
H_POL                   = vic_timing['h_pol'] == 'n' ? "-" : "+";

V_FRONT_PORCH           = vic_timing['v_front'];
V_SYNC_RND              = vic_timing['v_sync'];
V_BACK_PORCH            = vic_timing['v_back'];
V_POL                   = vic_timing['v_pol'] == 'n' ? "-" : "+";
```

Thank you very much for sharing, it is a very useful tool.

**Comment by xqworld** [comment]
I modified it, reference #42. Thanks

**Comment by tomverbeure** [comment]
Merged!
