### ISSUE TITLE
Shouldn't HBR3 be 8.1GHz ?

### ISSUE THREAD

**Issue by cpstar** [tomverbeure/tomverbeure.github.io#45]
https://github.com/tomverbeure/tomverbeure.github.io/blob/163fe116fbf0dd220a2f6f5bd3cc6236a0b35171/video_timings_calculator.html#L1176

The code was based on 8 000 000 000, and line 1182. So it may report a wrong result.
Shouldn't it be 8 1000 000 000?

**Comment by tomverbeure** [comment]
Yeah, that was an embarrassing typo. Fixed with 35c5ab0.

Thanks!
Tom

**Comment by cpstar** [comment]
line 1182 as well. 😁

**Comment by tomverbeure** [comment]
Done!
